### ISSUE TITLE
Misaligned tags

### ISSUE THREAD

**Issue by boh717** [epistrephein/Steam#13]
Hello,
grouping posts by tags has a problem. 
Here is a screenshot:
![steam](https://cloud.githubusercontent.com/assets/3520636/15449356/9bc97b2e-1f7b-11e6-84cf-27a73738609c.png)

I'm using your last version and Ghost 0.8.0.
If you need more information, just let me know.

Bye!

**Comment by epistrephein** [comment]
I pushed a fix for this along with the new 1.5.0 stable release.
Thanks for catching the bug.
