### ISSUE TITLE
Cannot change favicon

### ISSUE THREAD

**Issue by boh717** [epistrephein/Steam#5]
Hi,
I'm using your theme and I'm trying to change the default favicon.
As you describe in the README, I **replaced** the standard icon with my own one, preserving the name (favicon.ico). Moreover I deleted the apple touch icon file, also modifying partials/favicon-appletouchicon.hbs and deleted the corresponding line.
I restarted the service and deleted the cache. No success.

What am I missing? Is there any other setting that is overriding my modifications?

**Comment by epistrephein** [comment]
Hi there, can you try to replace the favicon line inside `partials/favicon-appletouchicon.hbs` with

`<link rel="shortcut icon" href="{{asset "img/favicon.ico"}}?v=2">`

This should force the cache reload, which I think it's the problem here.

**Comment by boh717** [comment]
It keeps loading the standard one.
With your modification, it attempts to load this one: https://runningcodes.net/assets/img/favicon.ico?v=2ceac22790?v=2

**Comment by boh717** [comment]
Solved.
I don't know why, but there was a problem with the .ico file.
Using .png fixed everything.
Thanks for your support.

**Comment by epistrephein** [comment]
I tried on mine and it worked, good to know you solved!
